services:
  orbeji_unusedroutes.log_routes_subscriber:
    class: Orbeji\UnusedRoutes\EventSubscriber\LogRoutesSubscriber
    arguments:
      $parameterBag: "@parameter_bag"
    tags:
      - { name: kernel.event_subscriber }
  Orbeji\UnusedRoutes\Command\RouteUsageCommand:
    autowire: true
    arguments: ['%unused_routes.file_path%']
    tags: [console.command]