services:
  orbeji_unusedroutes.usage_route_provider:
    class: Orbeji\UnusedRoutes\Provider\FileUsageRouterProvider
    arguments: ['%unused_routes.file_path%']

  Orbeji\UnusedRoutes\Provider\UsageRouteProviderInterface: '@orbeji_unusedroutes.usage_route_provider'

  orbeji_unusedroutes.log_routes_subscriber:
    class: Orbeji\UnusedRoutes\EventSubscriber\LogRoutesSubscriber
    arguments: ['@Orbeji\UnusedRoutes\Provider\UsageRouteProviderInterface']
    tags:
      - { name: kernel.event_subscriber }

  orbeji_unusedroutes.route_usage_command:
    class: Orbeji\UnusedRoutes\Command\RouteUsageCommand
    arguments: ['@Orbeji\UnusedRoutes\Provider\UsageRouteProviderInterface', '@router.default']
    tags: [console.command]