on: [push]
name: Static analysis

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: phpstan:1.2.0, cs2pr

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: PHPStan
        run: phpstan analyze --no-progress --error-format=checkstyle | cs2pr

  phpcs:
    name: PhpCS
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.3
          path: src/
          standard: psr12

  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer-normalize

      - name: Normalize
        run: composer-normalize --dry-run
