name: PHPUnit and Coverage Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install dependencies
      run: composer install

    - name: Run PHPUnit with coverage
      run: vendor/bin/phpunit --coverage-clover clover.xml

    - name: Coverage check
      run: vendor/bin/coverage-check clover.xml 100
